name: Python test

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: install pipenv
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv

    - name: install packages
      run: pipenv sync --dev

    - name: run test
      run: pipenv run pytest
